ClientId: '1465711556418474148'
ShowCoverArt: 1
ShowQualityTags: 0
ShowChapter: 0
ShowAudioLanguage: 1
EnableMetadataCleaner: 1
StrictLocalMode: 0
CustomJunkWords: ''
MinimalMode: 1
ShowNotifications: 1
Theme: dark_
Provider: Google
CustomUrl: ''
ButtonLabel: Search This
