theme: ''
disableNewStartMenuLayout: 0
controlStyles:
  - target: SecHealthUIAppShell.AppShell#SechealthUI
    styles:
      - Background:=$MainBgColor
  - target: Frame#frame > ContentPresenter
    styles:
      - Background=Transparent
  - target: Grid#ContentRoot > Border > Grid#ContentGrid
    styles:
      - Background=Transparent
      - BorderBrush=Transparent
  - target: Grid#PaneRoot
    styles:
      - Background:=$MainBgColor
  - target: TextBlock#title
    styles:
      - FontSize=28
      - FontWeight=SemiBold
  - target: TextBlock#subTitle
    styles:
      - FontSize=16
  - target: TextBlock#PageTitle
    styles:
      - FontSize=28
      - FontWeight=SemiBold
  - target: TextBlock#PageSubtitle
    styles:
      - FontSize=16
  - target: SecHealthUIAppShell.DashboardHostPage > Grid#DashboardHostPageParentGrid
    styles:
      - Background=Transparent
  - target: SecHealthUIAppShell.DashboardTileGridView#DashboardTileGridView > Border > ScrollViewer#ScrollViewer > Border#Root > Grid > ScrollContentPresenter#ScrollContentPresenter > ItemsPresenter > ItemsWrapGrid > GridViewItem > Windows.UI.Xaml.Controls.Primitives.ListViewItemPresenter#Root > Border
    styles:
      - Background=Transparent
  - target: SecHealthUIAppShell.DashboardTileListView#DashboardTileListView > Border > ScrollViewer#ScrollViewer > Border#Root > Grid > ScrollContentPresenter#ScrollContentPresenter > ItemsPresenter > ItemsStackPanel > ListViewItem > Windows.UI.Xaml.Controls.Primitives.ListViewItemPresenter#Root > Border
    styles:
      - Background=Transparent
  - target: SecHealthUIAppShell.ThreatPillar.ThreatProtectionPage > Grid > Grid
    styles:
      - Background=Transparent
  - target: SecHealthUIAppShell.ThreatPillar.ThreatAdvancedScanPage > Grid > Grid
    styles:
      - Background=Transparent
  - target: SecHealthUIAppShell.ThreatPillar.ThreatAllowedThreatPage > Grid > Grid
    styles:
      - Background=Transparent
  - target: SecHealthUIAppShell.ThreatPillar.ThreatSettingsPage > Grid > Grid
    styles:
      - Background=Transparent
  - target: SecHealthUIAppShell.ThreatPillar.DevVolumesDetailsPage > Grid > Grid
    styles:
      - Background=Transparent
  - target: SecHealthUIAppShell.ThreatPillar.ThreatExclusionsPage > Grid > Grid
    styles:
      - Background=Transparent
  - target: SecHealthUIAppShell.ThreatPillar.ThreatUpdatesPage > Grid > Grid
    styles:
      - Background=Transparent
  - target: SecHealthUIAppShell.ThreatPillar.ThreatRansomwarePage > Grid > Grid
    styles:
      - Background=Transparent
  - target: SecHealthUIAppShell.ThreatPillar.ThreatFolderGuardProtectedFoldersPage > Grid > Grid
    styles:
      - Background=Transparent
  - target: SecHealthUIAppShell.ThreatPillar.ThreatFolderGuardAllowAppPage > Grid > Grid
    styles:
      - Background=Transparent
  - target: SecHealthUIAppShell.AccountPillar.AccountPage > Grid > Grid
    styles:
      - Background=Transparent
  - target: SecHealthUIAppShell.FirewallPillar.FirewallPage > Grid > Grid
    styles:
      - Background=Transparent
  - target: SecHealthUIAppShell.FirewallPillar.FirewallDomainPage > Grid > Grid
    styles:
      - Background=Transparent
  - target: SecHealthUIAppShell.FirewallPillar.FirewallPrivatePage > Grid > Grid
    styles:
      - Background=Transparent
  - target: SecHealthUIAppShell.FirewallPillar.FirewallPublicPage > Grid > Grid
    styles:
      - Background=Transparent
  - target: SecHealthUIAppShell.AppBrowserPillar.AppBrowserPage > Grid > Grid
    styles:
      - Background=Transparent
  - target: SecHealthUIAppShell.AppBrowserPillar.SmartAppSettingsPage > Grid > Grid
    styles:
      - Background=Transparent
  - target: SecHealthUIAppShell.AppBrowserPillar.SmartScreenPuaSettingsPage > Grid > Grid
    styles:
      - Background=Transparent
  - target: SecHealthUIAppShell.AppBrowserPillar.ExploitMitigationPage > Grid > Grid
    styles:
      - Background=Transparent
  - target: SecHealthUIAppShell.HardwarePillar.HardwarePage > Grid > Grid
    styles:
      - Background=Transparent
  - target: SecHealthUIAppShell.HardwarePillar.ManageCoreSecurityPage > Grid > Grid
    styles:
      - Background=Transparent
  - target: SecHealthUIAppShell.HardwarePillar.ManageTPMPage > ScrollViewer > Border#Root > Grid > ScrollContentPresenter#ScrollContentPresenter > Grid > Grid
    styles:
      - Background=Transparent
  - target: SecHealthUIAppShell.HardwarePillar.AdvancedTpmPage > Grid > Grid
    styles:
      - Background=Transparent
  - target: SecHealthUIAppShell.HealthPillar.HealthPage > Grid > Grid
    styles:
      - Background=Transparent
  - target: SecHealthUIAppShell.FamilyPillar.FamilyPage > Grid > Grid
    styles:
      - Background=Transparent
  - target: SecHealthUIAppShell.SettingsPillar.HistoryPage > Grid > StackPanel > Grid#ContentGrid
    styles:
      - Background=Transparent
  - target: SecHealthUIAppShell.SettingsPillar.SettingsPage > Grid > Grid
    styles:
      - Background=Transparent
  - target: SecHealthUIAppShell.SettingsPillar.ProviderPage > Grid > Grid
    styles:
      - Background=Transparent
  - target: SecHealthUIAppShell.SettingsPillar.NotificationPage > Grid > Grid
    styles:
      - Background=Transparent
  - target: SecHealthUIAppShell.SettingsPillar.AboutPage > Grid
    styles:
      - Background=Transparent
webContentStyles:
  - target: ''
    styles:
      - ''
webContentCustomJs: ''
styleConstants:
  - MainBgColor=<AcrylicBrush BackgroundSource="HostBackdrop" TintColor="{StaticResource SystemChromeAltHighColor}" TintOpacity="0.8" FallbackColor="{StaticResource SystemChromeMediumColor}" />
resourceVariables:
  - variableKey: ''
    value: ''